export const sampleUsers = [
  {
    id: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    name: "Alice Johnson",
    email: "alice@example.com",
    password: "hashedpassword1",
    isPasswordByAdmin: false,
    role: "admin",
    lastActiveAt: new Date(),
    totalLeads: 12,
    totalAssignedLeads: 5,
  },
  {
    id: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    name: "Bob Smith",
    email: "bob@example.com",
    password: "hashedpassword2",
    isPasswordByAdmin: true,
    role: "sales",
    lastActiveAt: new Date(),
    totalLeads: 20,
    totalAssignedLeads: 10,
  },
  {
    id: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    name: "Charlie Nguyen",
    email: "charlie.nguyen@example.com",
    password: "hashedpassword3",
    isPasswordByAdmin: false,
    role: "sales",
    lastActiveAt: new Date(),
    totalLeads: 8,
    totalAssignedLeads: 4,
  },
  {
    id: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    name: "Diana Lopez",
    email: "diana.lopez@example.com",
    password: "hashedpassword4",
    isPasswordByAdmin: true,
    role: "marketing",
    lastActiveAt: new Date(),
    totalLeads: 15,
    totalAssignedLeads: 9,
  },
];

export const sampleLeads = [
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c3g3h2j3-3c5d-6h24-1g4e-c03456ghi333",
    leadName: "John Doe",
    industary: "Software",
    position: "CTO",
    source: "LinkedIn",
    companyName: "TechCorp",
    status: "Contacted",
    mobile: "+1-123-456-7890",
    email: "john.doe@techcorp.com",
    website: "https://techcorp.com",
    note: "Interested in enterprise plan.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "USA",
    followUpCounter: 2,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "d4i4j3k4-4d6e-7i35-2h5f-d04567jkl444",
    leadName: "Emily Carter",
    industary: "Finance",
    position: "CFO",
    source: "Webinar",
    companyName: "FinTrust",
    status: "New",
    mobile: "+44-20-7946-0958",
    email: "emily.carter@fintrust.co.uk",
    website: "https://fintrust.co.uk",
    note: "Follow-up scheduled next week.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "UK",
    followUpCounter: 0,
    createdBy: "b2f2d1e9-2b4c-5g13-0f3d-b92345def222",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "e5j5k4l5-5e7f-8j46-3i6g-e05678lmn555",
    leadName: "Rajesh Verma",
    industary: "E-commerce",
    position: "Founder",
    source: "Referral",
    companyName: "ShopVerse",
    status: "In Progress",
    mobile: "+91-9876543210",
    email: "rajesh@shopverse.in",
    website: "https://shopverse.in",
    note: "Requested demo for next week.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "India",
    followUpCounter: 1,
    createdBy: "a1f1c0f8-1a3b-4f02-9e2c-a91234abc111",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "h8m8n7o8-8h0i-1m79-6l9j-h08901rst888",
    leadName: "Mohammed Al-Farsi",
    industary: "Healthcare",
    position: "CEO",
    source: "Conference",
    companyName: "WellnessHub",
    status: "Follow-Up Due",
    mobile: "+971-50-123-4567",
    email: "mohammed@wellnesshub.ae",
    website: "https://wellnesshub.ae",
    note: "Wants pricing details for enterprise version.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "UAE",
    followUpCounter: 3,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "i9n9o8p9-9i1j-2n80-7m0k-i09123tuv999",
    leadName: "Sofia Rossi",
    industary: "Fashion",
    position: "Marketing Director",
    source: "Instagram",
    companyName: "ModaBella",
    status: "Demo Scheduled",
    mobile: "+39-06-1234-5678",
    email: "sofia.rossi@modabella.it",
    website: "https://modabella.it",
    note: "Interested in influencer marketing tools.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Italy",
    followUpCounter: 1,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "j1o0p9q1-0j2k-3o91-8n1l-j01234uvw000",
    leadName: "Lucas Kim",
    industary: "Logistics",
    position: "Operations Manager",
    source: "Cold Email",
    companyName: "ShipMax",
    status: "Not Interested",
    mobile: "+82-10-1234-5678",
    email: "lucas.kim@shipmax.kr",
    website: "https://shipmax.kr",
    note: "Already using a competitor tool.",
    idDeleted: false,
    isAssigned: true,
    gender: "Male",
    country: "South Korea",
    followUpCounter: 2,
    createdBy: "f6k6l5m6-6f8g-9k57-4j7h-f06789opq666",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "k2p1q0r2-1k3l-4p02-9o2m-k12345vwx111",
    leadName: "Ava Thompson",
    industary: "Education",
    position: "Program Coordinator",
    source: "Newsletter",
    companyName: "EduWise",
    status: "Interested",
    mobile: "+61-2-9876-5432",
    email: "ava.thompson@eduwise.edu.au",
    website: "https://eduwise.edu.au",
    note: "Wants a quote for student plan.",
    idDeleted: false,
    isAssigned: false,
    gender: "Female",
    country: "Australia",
    followUpCounter: 0,
    createdBy: "g7l7m6n7-7g9h-0l68-5k8i-g07890qrs777",
    modifiedAt: new Date(),
    createdAt: new Date(),
  },
];
